android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=33

# 跳过资源合并错误
android.enableR8.fullMode=false
android.nonTransitiveRClass=false
android.nonFinalResIds=false

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.caching=true
