include ':app'
rootProject.name = "TimeTracker"

// 为所有项目添加仓库配置
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }  // 添加JitPack仓库支持MPAndroidChart
    }
}
